@echo off
echo Conectando-se ao servidor e atualizando a API...
ssh -t admin-agendoaqui@servidor.1nfotech.link  "cd htdocs && cd api-agendoaqui.infotech.app.br && cd API-AGENDOAQUI && git pull && npm install && npx tsc && pm2 restart API-AGENDOAQUI"