@echo off
echo Conectando-se ao servidor e atualizando a API...
ssh -t admin-agendoaqui@servidor.1nfotech.link "cd ~/htdocs/api.agendoaqui.infotech.app.br/API-AGENDOAQUI && git pull && npx tsc && pm2 restart API-AGENDOAQUI"